# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
docs/api/backend-generated/v1/openapi.yaml:
  info-license-strict:
    - '#/info/license/url'
  no-server-example.com:
    - '#/servers/0/url'
  operation-4xx-response:
    - '#/paths/~1api~1v1~1zones~1{id}/get/responses'
    - '#/paths/~1api~1v1~1zones~1{id}/put/responses'
    - '#/paths/~1api~1v1~1zones~1{id}/delete/responses'
    - '#/paths/~1api~1v1~1tokens~1selection/put/responses'
    - '#/paths/~1api~1v1~1memberships~1{id}/get/responses'
    - '#/paths/~1api~1v1~1memberships~1{id}/put/responses'
    - '#/paths/~1api~1v1~1memberships~1{id}/delete/responses'
    - '#/paths/~1api~1v1~1me~1profile/get/responses'
    - '#/paths/~1api~1v1~1me~1profile/put/responses'
    - '#/paths/~1api~1v1~1fonts~1{key}/get/responses'
    - '#/paths/~1api~1v1~1fonts~1{key}/put/responses'
    - '#/paths/~1api~1v1~1fonts~1{key}/delete/responses'
    - '#/paths/~1api~1v1~1dashboard~1{id}/get/responses'
    - '#/paths/~1api~1v1~1dashboard~1{id}/put/responses'
    - '#/paths/~1api~1v1~1dashboard~1{id}/delete/responses'
    - '#/paths/~1api~1v1~1zones/get/responses'
    - '#/paths/~1api~1v1~1zones/post/responses'
    - '#/paths/~1api~1v1~1public~1forgot-password/post/responses'
    - '#/paths/~1api~1v1~1memberships/get/responses'
    - '#/paths/~1api~1v1~1memberships/post/responses'
    - '#/paths/~1api~1v1~1me~1password/post/responses'
    - '#/paths/~1api~1v1~1fonts/get/responses'
    - '#/paths/~1api~1v1~1fonts/post/responses'
    - '#/paths/~1api~1v1~1events/get/responses'
    - '#/paths/~1api~1v1~1dashboard/get/responses'
    - '#/paths/~1api~1v1~1dashboard/post/responses'
    - '#/paths/~1api~1v1~1admin~1echo/post/responses'
    - '#/paths/~1v1~1i18n~1messages~1{key}/get/responses'
    - '#/paths/~1v1~1i18n~1locales/get/responses'
    - '#/paths/~1api/get/responses'
    - '#/paths/~1api~1v1~1zones~1paged/get/responses'
    - '#/paths/~1api~1v1~1tokens/get/responses'
    - '#/paths/~1api~1v1~1seller-codes~1paged/get/responses'
    - '#/paths/~1api~1v1~1roles/get/responses'
    - '#/paths/~1api~1v1~1public~1landing/get/responses'
    - '#/paths/~1api~1v1~1memberships~1paged/get/responses'
    - '#/paths/~1api~1v1~1me~1locale/get/responses'
    - '#/paths/~1api~1v1~1health/get/responses'
    - '#/paths/~1api~1v1~1events~1nearby/get/responses'
    - '#/paths/~1api~1v1~1events~1list/get/responses'
    - '#/paths/~1api~1v1~1dashboard~1overview/get/responses'
    - '#/paths/~1api~1v1~1auth~1status/get/responses'
  operation-summary:
    - '#/paths/~1api~1v1~1tokens~1selection/put/summary'
    - '#/paths/~1api~1v1~1themes~1{id}/get/summary'
    - '#/paths/~1api~1v1~1themes~1{id}/put/summary'
    - '#/paths/~1api~1v1~1themes~1{id}/delete/summary'
    - '#/paths/~1api~1v1~1themes~1{id}~1activate/put/summary'
    - '#/paths/~1api~1v1~1me~1profile/get/summary'
    - '#/paths/~1api~1v1~1me~1profile/put/summary'
    - '#/paths/~1api~1v1~1fonts~1{key}/get/summary'
    - '#/paths/~1api~1v1~1fonts~1{key}/put/summary'
    - '#/paths/~1api~1v1~1fonts~1{key}/delete/summary'
    - '#/paths/~1api~1v1~1dashboard~1{id}/get/summary'
    - '#/paths/~1api~1v1~1dashboard~1{id}/put/summary'
    - '#/paths/~1api~1v1~1dashboard~1{id}/delete/summary'
    - '#/paths/~1api~1v1~1themes/get/summary'
    - '#/paths/~1api~1v1~1themes/post/summary'
    - '#/paths/~1api~1v1~1public~1forgot-password/post/summary'
    - '#/paths/~1api~1v1~1me~1password/post/summary'
    - '#/paths/~1api~1v1~1fonts/get/summary'
    - '#/paths/~1api~1v1~1fonts/post/summary'
    - '#/paths/~1api~1v1~1dashboard/get/summary'
    - '#/paths/~1api~1v1~1dashboard/post/summary'
    - '#/paths/~1api~1v1~1admin~1echo/post/summary'
    - '#/paths/~1v1~1i18n~1messages~1{key}/get/summary'
    - '#/paths/~1v1~1i18n~1locales/get/summary'
    - '#/paths/~1api/get/summary'
    - '#/paths/~1api~1v1~1tokens/get/summary'
    - '#/paths/~1api~1v1~1themes~1active/get/summary'
    - '#/paths/~1api~1v1~1roles/get/summary'
    - '#/paths/~1api~1v1~1public~1landing/get/summary'
    - '#/paths/~1api~1v1~1me~1locale/get/summary'
    - '#/paths/~1api~1v1~1health/get/summary'
    - '#/paths/~1api~1v1~1dashboard~1overview/get/summary'
