# File: auth-status.yaml
# Purpose: Auth status endpoint definition
openapi: 3.0.3
x-path: /api/v1/auth/status
paths:
  /api/v1/auth/status:
    get:
      tags: [auth]
      summary: Authentication status
      operationId: authStatus
      responses:
        '200':
          description: Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
        '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
