# File: configuration-item.yaml
# Purpose: Item resource for a single configuration entry identified by
# key. Updates require If-Match and are idempotent via header. All
# Rights Reserved. Arodi Emmanuel
/api/v1/configuration/{key}:
  parameters:
    - name: key
      in: path
      required: true
      schema: { type: string }
  get:
    summary: Get configuration entry
    tags: [configuration]
    security: [{ bearerAuth: [] }]
    responses:
      '200':
        description: OK
        headers:
          ETag:
            description: Strong ETag of response
            schema: { type: string }
      '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
      '403': { $ref: ../components/responses/common.yaml#/Forbidden }
      '404': { $ref: ../components/responses/common.yaml#/NotFound }
  put:
    summary: Update configuration entry
    tags: [configuration]
    security: [{ bearerAuth: [] }]
    parameters:
      - $ref: ../components/parameters/common-headers.yaml#/IfMatch
      - $ref: ../components/parameters/common-headers.yaml#/IdempotencyKey
    requestBody:
      required: true
      content:
        application/json:
          schema: { $ref: ../components/schemas/config-update.yaml }
    responses:
      '200':
        description: Updated
        headers:
          ETag:
            description: Strong ETag of response
            schema: { type: string }
      '400': { $ref: ../components/responses/common.yaml#/BadRequest }
      '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
      '403': { $ref: ../components/responses/common.yaml#/Forbidden }
      '404': { $ref: ../components/responses/common.yaml#/NotFound }
      '412': { $ref: ../components/responses/common.yaml#/PreconditionFailed }
      '428': { $ref: ../components/responses/common.yaml#/PreconditionRequired }
  delete:
    summary: Delete configuration entry
    tags: [configuration]
    security: [{ bearerAuth: [] }]
    parameters:
      - $ref: ../components/parameters/common-headers.yaml#/IfMatch
      - $ref: ../components/parameters/common-headers.yaml#/IdempotencyKey
    responses:
      '204': { description: No Content }
      '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
      '403': { $ref: ../components/responses/common.yaml#/Forbidden }
      '404': { $ref: ../components/responses/common.yaml#/NotFound }
      '409': { $ref: ../components/responses/common.yaml#/Conflict }
      '412': { $ref: ../components/responses/common.yaml#/PreconditionFailed }
      '428': { $ref: ../components/responses/common.yaml#/PreconditionRequired }
