# File: configuration-collection.yaml
# Purpose: Collection resource for listing configuration entries and
# creating new keys where allowed. Enforces typed values and paging to
# keep responses small. All Rights Reserved. Arodi Emmanuel
/api/v1/configuration:
  get:
    summary: List configuration entries
    operationId: getConfiguration
    tags: [configuration]
    security: [{ bearerAuth: [] }]
    responses:
      '200':
        description: OK
        headers:
          ETag:
            $ref: ../components/headers.yaml#/ETag
      '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
      '403': { $ref: ../components/responses/common.yaml#/Forbidden }
  post:
    summary: Create configuration entry
    operationId: postConfiguration
    tags: [configuration]
    security: [{ bearerAuth: [] }]
    parameters:
      - $ref: ../components/parameters/common-headers.yaml#/IdempotencyKey
    requestBody:
      required: true
      content:
        application/json:
          schema: { $ref: ../components/schemas/config-entry.yaml }
    responses:
      '201': { description: Created }
      '400': { $ref: ../components/responses/common.yaml#/BadRequest }
      '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
      '403': { $ref: ../components/responses/common.yaml#/Forbidden }
      '409': { $ref: ../components/responses/common.yaml#/Conflict }
