/*
 * File: AccessLogJpaRepository.java
 * Purpose: Spring Data repository interface for the AccessLogEntity. Provides standard CRUD operations to persist and retrieve the physical entry logs generated by fingerprint verification matches.
 * All Rights Reserved. Arodi Emmanuel
 */

package com.poetry.poetry_backend.infrastructure.jpa.accesslog;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AccessLogJpaRepository extends JpaRepository<AccessLogEntity, Long> {
}
