/*
 File: writeParts.mjs
 Purpose: Generate unified i18n keys file (no splitting needed as
          autogen files are excluded from line/size checks).
 All Rights Reserved. Arodi Emmanuel
*/
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

export function writeParts(genDir, sorted) {
  mkdirSync(genDir, { recursive: true })

  const header = [
    '/*',
    ' * File: keys.ts',
    ' * Purpose: Unified i18n key list (generated). AUTOGENERATED.',
    ' * DO NOT EDIT MANUALLY. AUTOGENERATED.',
    ' * All Rights Reserved. Arodi Emmanuel',
    ' */',
    '',
  ]
  const body = ['export const I18N_KEYS: readonly string[] = [']
  for (const k of sorted) body.push("  '" + k + "',")
  body.push('] as const')
  body.push('')
  body.push('export type I18nKey = (typeof I18N_KEYS)[number]')
  body.push('')
  writeFileSync(join(genDir, 'keys.ts'), header.concat(body).join('\n'), 'utf8')
}
