# File: openapi-v1.yaml
# Purpose: OpenAPI v1 root that references modular parts. All Rights Reserved.
openapi: 3.0.3
info:
  title: Poetry API
  version: 1.0.0
  license:
    name: Proprietary
    url: https://example.com/license
servers:
  - url: /api
tags:
  - name: system
    description: System and health endpoints
  - name: users
    description: User management endpoints
  - name: auth
    description: Authentication endpoints
  - name: organizations
    description: Organization management endpoints
  - name: configuration
    description: System configuration endpoints
paths:
  /:
    $ref: ./openapi/paths/api-index.yaml
  /v1/health:
    $ref: ./openapi/paths/api.yaml#/~1api~1v1~1health
  /v1/auth/login:
    $ref: ./openapi/paths/auth-login.yaml#/~1api~1v1~1auth~1login
  /v1/auth/refresh:
    $ref: ./openapi/paths/auth-refresh.yaml#/~1api~1v1~1auth~1refresh
  /v1/auth/me:
    $ref: ./openapi/paths/auth-me.yaml#/~1api~1v1~1auth~1me
  /v1/auth/logout:
    $ref: ./openapi/paths/auth-logout.yaml#/~1api~1v1~1auth~1logout
  /v1/users:
    $ref: ./openapi/paths/users-collection.yaml#/~1api~1v1~1users
  /v1/users/{id}:
    $ref: ./openapi/paths/users-item.yaml#/~1api~1v1~1users~1{id}
  /v1/configuration:
    $ref: ./openapi/paths/configuration-collection.yaml#/~1api~1v1~1configuration
  /v1/configuration/{key}:
    $ref: ./openapi/paths/configuration-item.yaml#/~1api~1v1~1configuration~1{key}
  /v1/organizations:
    $ref: ./openapi/paths/organizations-collection.yaml#/~1api~1v1~1organizations
  /v1/organizations/{id}:
    $ref: ./openapi/paths/organizations-item.yaml#/~1api~1v1~1organizations~1{id}
components:
  securitySchemes:
    $ref: ./openapi/components/securitySchemes.yaml
  parameters:
    $ref: ./openapi/components/parameters/common-headers.yaml
  headers:
    $ref: ./openapi/components/headers.yaml
  schemas:
    Error:
      $ref: ./openapi/components/schemas/error.yaml
    Page:
      $ref: ./openapi/components/schemas/paging.yaml
    ConfigEntry:
      $ref: ./openapi/components/schemas/config-entry.yaml
    ConfigUpdate:
      $ref: ./openapi/components/schemas/config-update.yaml
    Organization:
      $ref: ./openapi/components/schemas/organization.yaml
    PageOrganization:
      $ref: ./openapi/components/schemas/page-organization.yaml
    User:
      $ref: ./openapi/components/schemas/user.yaml
    UserCreate:
      $ref: ./openapi/components/schemas/user-create.yaml
    UserUpdate:
      $ref: ./openapi/components/schemas/user-update.yaml
    PageUser:
      $ref: ./openapi/components/schemas/page-user.yaml
  responses:
    $ref: ./openapi/components/responses/common.yaml
security:
  - bearerAuth: []
