# File: openapi-v1.yaml
# Purpose: OpenAPI v1 root that references modular parts. All Rights Reserved.
openapi: 3.0.3
info:
  title: Poetry API
  version: 1.0.0
  license:
    name: Proprietary
    url: https://example.com/license
servers:
  - url: /api
tags:
  - name: system
    description: System and health endpoints
  - name: users
    description: User management endpoints
  - name: auth
    description: Authentication endpoints
  - name: organizations
    description: Organization management endpoints
  - name: configuration
    description: System configuration endpoints
  - name: themes
    description: UI theme management endpoints
paths:
  /:
    $ref: ./openapi/paths/api-index.yaml
  /v1/health:
    $ref: ./openapi/paths/api.yaml#/~1api~1v1~1health
  /v1/auth/login:
    $ref: ./openapi/paths/auth-login.yaml#/~1api~1v1~1auth~1login
  /v1/auth/refresh:
    $ref: ./openapi/paths/auth-refresh.yaml#/~1api~1v1~1auth~1refresh
  /v1/auth/me:
    $ref: ./openapi/paths/auth-me.yaml#/~1api~1v1~1auth~1me
  /v1/auth/logout:
    $ref: ./openapi/paths/auth-logout.yaml#/~1api~1v1~1auth~1logout
  /v1/users:
    $ref: ./openapi/paths/users-collection.yaml#/~1api~1v1~1users
  /v1/users/{id}:
    $ref: ./openapi/paths/users-item.yaml#/~1api~1v1~1users~1{id}
  /v1/configuration:
    $ref: ./openapi/paths/configuration-collection.yaml#/~1api~1v1~1configuration
  /v1/configuration/{key}:
    $ref: ./openapi/paths/configuration-item.yaml#/~1api~1v1~1configuration~1{key}
  /v1/organizations:
    $ref: ./openapi/paths/organizations-collection.yaml#/~1api~1v1~1organizations
  /v1/organizations/{id}:
    $ref: ./openapi/paths/organizations-item.yaml#/~1api~1v1~1organizations~1{id}
  /v1/themes:
    $ref: ./openapi/paths/themes-collection.yaml#/~1api~1v1~1themes
  /v1/themes/{id}:
    $ref: ./openapi/paths/themes-item.yaml#/~1api~1v1~1themes~1{id}
  /v1/themes/{id}/activate:
    $ref: ./openapi/paths/themes-activate.yaml#/~1api~1v1~1themes~1{id}~1activate
  /v1/themes/active:
    $ref: ./openapi/paths/themes-active.yaml#/~1api~1v1~1themes~1active
  /v1/tokens:
    $ref: ./openapi/paths/tokens-collection.yaml
  /v1/tokens/selection:
    $ref: ./openapi/paths/tokens-selection.yaml
components:
  securitySchemes:
    $ref: ./openapi/components/securitySchemes.yaml
  parameters:
    $ref: ./openapi/components/parameters/common-headers.yaml
  headers:
    $ref: ./openapi/components/headers.yaml
  schemas:
    Error:
      $ref: ./openapi/components/schemas/error.yaml
    Page:
      $ref: ./openapi/components/schemas/paging.yaml
    ConfigEntry:
      $ref: ./openapi/components/schemas/config-entry.yaml
    ConfigUpdate:
      $ref: ./openapi/components/schemas/config-update.yaml
    Organization:
      $ref: ./openapi/components/schemas/organization.yaml
    PageOrganization:
      $ref: ./openapi/components/schemas/page-organization.yaml
    User:
      $ref: ./openapi/components/schemas/user.yaml
    UserCreate:
      $ref: ./openapi/components/schemas/user-create.yaml
    UserUpdate:
      $ref: ./openapi/components/schemas/user-update.yaml
    PageUser:
      $ref: ./openapi/components/schemas/page-user.yaml
    Theme:
      $ref: ./openapi/components/schemas/theme.yaml
    ThemeCreate:
      $ref: ./openapi/components/schemas/theme-create.yaml
    ThemeUpdate:
      $ref: ./openapi/components/schemas/theme-update.yaml
    UITokens:
      type: object
      description: Aggregate UI tokens payload.
      properties:
        themes: { type: array, items: { $ref: '#/components/schemas/Theme' } }
        fonts:
          type: array
          description: Available font assets for UI configuration.
          items:
            type: object
            properties:
              key: { type: string }
              label: { type: string }
              woff2Url: { type: string, format: uri }
              weights:
                type: array
                items: { type: integer }
              hash:
                { type: string, description: Stable hash of font file contents }
              preloadDefault:
                type: boolean
                description:
                  Indicates the single baseline font guaranteed to be preloaded
                  offline.
              integrity:
                type: string
                description:
                  Optional integrity value (sha256-...) for future strict
                  verification.
            required: [key, label, woff2Url, weights, hash]
        fontSizes:
          { type: array, items: { type: object, additionalProperties: true } }
        fontWeights: { type: array, items: { type: string } }
        spacings:
          { type: array, items: { type: object, additionalProperties: true } }
        radius:
          { type: array, items: { type: object, additionalProperties: true } }
        shadows:
          { type: array, items: { type: object, additionalProperties: true } }
        current:
          type: object
          properties:
            theme: { type: string }
            font: { type: string }
            fontSize: { type: string }
            spacing: { type: string }
            radius: { type: string }
            shadow: { type: string }
    UpdateSelectionRequest:
      type: object
      required: [theme, font, fontSize, spacing, radius, shadow]
      properties:
        theme: { type: string }
        font: { type: string }
        fontSize: { type: string }
        spacing: { type: string }
        radius: { type: string }
        shadow: { type: string }
  responses:
    $ref: ./openapi/components/responses/common.yaml
security:
  - bearerAuth: []
