# File: openapi-v1.yaml
# Purpose: OpenAPI v1 root that references modular parts. All Rights Reserved.
openapi: 3.0.3
info:
  title: Poetry API
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: system
  - name: users
  - name: auth
  - name: organizations
  - name: configuration
paths:
  /:
    $ref: ./openapi/paths/api-index.yaml
  /v1/health:
    $ref: ./openapi/paths/api.yaml#/api/v1/health
  /v1/users:
    $ref: ./openapi/paths/users-collection.yaml#/api/v1/users
  /v1/users/{id}:
    $ref: ./openapi/paths/users-item.yaml#/api/v1/users/{id}
components:
  securitySchemes:
    $ref: ./openapi/components/securitySchemes.yaml
  parameters:
    $ref: ./openapi/components/parameters/common-headers.yaml
  schemas:
    Error:
      $ref: ./openapi/components/schemas/error.yaml
    Page:
      $ref: ./openapi/components/schemas/paging.yaml
security:
  - bearerAuth: []
