#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# File: .husky/pre-push
# Purpose: Ensure quality gates before pushing.
# All Rights Reserved. Arodi Emmanuel

npm run test || exit 1
npm run typecheck || exit 1
npm run build || exit 1
npm run openapi:validate || exit 1
npm run sdk:check || exit 1
