# File: config-entry.yaml
# Purpose: Defines ConfigEntry domain schema for configuration items.
# Represents a typed key/value pair with versioning and audit info used
# to control platform behavior. This aligns with domain rules about type
# safety and change tracking. All Rights Reserved. Arodi Emmanuel
title: ConfigEntry
type: object
properties:
  key: { type: string }
  value: { type: string }
  type: { type: string, enum: [string, number, boolean, json] }
  version: { type: integer }
  updatedAt: { type: string, format: date-time }
  updatedBy: { type: string }
required: [key, value, type, version]
