# File: admin-echo.yaml
# Purpose: Real admin echo endpoint definition.
openapi: 3.0.3
x-path: /api/v1/admin/echo
paths:
  /api/v1/admin/echo:
    post:
      tags: [admin]
      summary: Echo a message
      operationId: adminEcho
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message:
                  type: string
                  minLength: 1
                  maxLength: 512
      responses:
        '200':
          description: Echoed message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400': { $ref: ../components/responses/common.yaml#/BadRequest }
        '401': { $ref: ../components/responses/common.yaml#/Unauthorized }
